config/routes.rb
Rails.application.routes.draw do
  root to: 'front#index'

  devise_for :users

  get 'messanger/index'
  get 'messanger/:id', to: 'messanger#conversation', as: 'messenger'
  post 'create_message', to: 'messanger#create'

  scope '/admin' do
    resources :users
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :from, class_name: 'User'
  belongs_to :to, class_name: 'User'

  after_initialize :init_attributes

  scope :between, -> (user_1_id, user_2_id) {
    where(from_id: [user_1_id, user_2_id], to_id: [user_1_id, user_2_id])
  }

  scope :unread_to, -> (to_id) {
    where(to_id: to_id, readed: false)
  }

  scope :by_from_and_to, ->(from_id, to_id) { where(from_id: from_id, to_id: to_id) }

  def self.mark_all_as_readed(from_id, to_id)
    by_from_and_to(from_id, to_id).update_all(readed: true)
  end

  private

  def init_attributes
    self.readed = false if readed.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :init_attributes

  has_many :messages_from_me, class_name: 'Message', foreign_key: 'from_id'

  scope :not_locked_and_except_user_ids, -> (user_ids) { where(locked: false).where.not(id: user_ids) }

  def self.with_new_messages(user_id)
    not_locked_and_except_user_ids(user_id)
      .joins(:messages_from_me).merge(Message.unread_to(user_id))
  end

  def full_name
    name || email
  end

  private

  def init_attributes
    self.admin = false if admin.nil?
    self.locked = false if locked.nil?
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_administrator

  private

  def check_administrator
    unless user_is_admin?
      redirect_to root_path, alert: 'You are not administrator'
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  helper_method :user_is_admin?

  def user_is_admin?
    user_signed_in? && current_user.admin?
  end

  protected

  def configure_permitted_parameters
    user_additional_params = [:name, :sex, :birthday]
    devise_parameter_sanitizer.permit(:sign_up, keys: user_additional_params)
    devise_parameter_sanitizer.permit(:account_update, keys: user_additional_params)
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < AdminController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @messages = Message.all
    respond_with(@messages)
  end

  def show
    respond_with(@message)
  end

  def new
    @message = Message.new
    respond_with(@message)
  end

  def edit
  end

  def create
    @message = Message.new(message_params)
    @message.save
    respond_with(@message)
  end

  def update
    @message.update(message_params)
    respond_with(@message)
  end

  def destroy
    @message.destroy
    respond_with(@message)
  end

  private
    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:from_id, :to_id, :readed, :body)
    end
end

app/controllers/messanger_controller.rb
class MessangerController < ApplicationController
  respond_to :html, :js

  def index
    @users_with_new_messages = User.with_new_messages(current_user.id).distinct
    @users = User.not_locked_and_except_user_ids(@users_with_new_messages.map(&:id) << current_user.id)
  end

  def conversation
    Message.mark_all_as_readed(params[:id], current_user.id)
    @interlocutor = User.find(params[:id])
    @messages = Message.between(current_user.id, @interlocutor.id).order(created_at: :desc)
    @message = Message.new(from: current_user, to: @interlocutor)
  end

  def create
    @message = Message.create(message_params)
    redirect_to messenger_path(@message.to_id)
  end

  private

  def message_params
    params.require(:message).permit(:to_id, :body).merge(from_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @users = User.all
    respond_with(@users)
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
    respond_with(@user)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    permitted = params.require(:user).permit(:email, :password, :admin, :locked, :name, :sex, :birthday)
    permitted.delete(:password) if permitted[:password].blank?
    permitted
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/front/index.html.haml
%h1 Welcome to the best app ever :)

- if user_signed_in? && User.with_new_messages(current_user.id).any?
  = link_to 'You have new messages', messanger_index_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Messenger"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/") Messenger
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            - if user_signed_in?
              %li= link_to 'Messenger', messanger_index_path
              %li= link_to 'Account', edit_user_registration_path
              %li= link_to 'Sign out', destroy_user_session_path, method: :delete
              - if user_is_admin?
                %li= link_to 'Users', users_path
                %li= link_to 'Messages', messages_path
            - else
              %li= link_to 'Sign in', new_user_session_path
              %li= link_to 'Sign up', new_user_registration_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

app/views/messages/_form.html.haml
= simple_form_for @message, :html => { :class => 'form-horizontal' } do |f|
  = f.association :from, label_method: :full_name
  = f.association :to, label_method: :full_name
  = f.input :readed
  = f.input :body
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), messages_path, :class => 'btn btn-default'

app/views/messages/edit.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/messages/index.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:from_id)
      %th= model_class.human_attribute_name(:to_id)
      %th= model_class.human_attribute_name(:readed)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @messages.each do |message|
      %tr
        %td= link_to message.id, message_path(message)
        %td= message.from.full_name
        %td= message.to.full_name
        %td= message.readed
        %td= message.body
        %td=l message.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), message_path(message), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_message_path(message), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(message), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_message_path, :class => 'btn btn-primary'

app/views/messages/new.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/messages/show.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:from_id) + ':'
  %br
  = @message.from.full_name
%p
  %strong= model_class.human_attribute_name(:to_id) + ':'
  %br
  = @message.to.full_name
%p
  %strong= model_class.human_attribute_name(:readed) + ':'
  %br
  = @message.readed
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @message.body


= link_to t('.back', :default => t("helpers.links.back")), messages_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_message_path(@message), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(@message), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/messanger/_messages.html.haml
- @messages.each do |message|
  %p{class: (message.from_id == current_user.id ? 'text-right' : 'text-left')}= message.body

app/views/messanger/conversation.html.haml
.col-xs-12.text-center
  #refresh-messages.btn.btn-primary refresh messages

= simple_form_for @message, url: create_message_path do |f|
  = f.hidden_field :to_id
  .row
    .col-xs-11
      = f.input :body, label: false
    .col-xs-1#send-message-button
      = f.submit 'Send', class: 'btn btn-success'
#message-history
  = render 'messages'

app/views/messanger/conversation.js.erb
$('#message-history').html('<%=j render('messages') %>')

app/views/messanger/index.html.haml
= link_to 'refresh message list', messanger_index_path
- if @users_with_new_messages.any?
  %h2 You receive new messages from users:
  %ul.list-unstyled
    - @users_with_new_messages.each do |user|
      %li
        = link_to user.full_name, messenger_path(user.id)

%h2 Select interlocutor to start conversation
%ul.list-unstyled
  - @users.each do |user|
    %li
      = link_to user.full_name, messenger_path(user.id)

app/views/users/_additional_fields.html.haml
= f.input :name
= f.input :sex, collection: %w(Male Female)
= f.input :birthday, start_year: Date.today.year - 12, end_year: Date.today.year - 110

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.input :email
  = f.input :admin
  = f.input :locked
  = render partial: 'additional_fields', locals: {f: f}
  = f.input :password
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:admin)
      %th= model_class.human_attribute_name(:locked)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.name
        %td= user.email
        %td= user.admin
        %td= user.locked
        %td
          = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:admin) + ':'
  %br
  = @user.admin
%p
  %strong= model_class.human_attribute_name(:locked) + ':'
  %br
  = @user.locked
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @user.name
%p
  %strong= model_class.human_attribute_name(:sex) + ':'
  %br
  = @user.sex
%p
  %strong= model_class.human_attribute_name(:birthday) + ':'
  %br
  = @user.birthday
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip


= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'